name: CI                            
on:
branch
  pull_request:
    branches: [ master ]     
jobs:                    
  build:              
    runs-on: ubuntu-latest
    steps:                        
      - uses: actions/checkout@v2
      
      - name: npm install ci       
        run: npm i        

      - name: Deploy to gh-pages
        run: |        
           git remote set-url origin https://git:${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
           npm run deploy
